### ISSUE TITLE
Update and Finish MarketingAI

### ISSUE THREAD

**Issue by sandviklee** [CogitoNTNU/web-frontend#11]
The MarketingAI design was not in its finished state when previewed in the presentation.

**Acceptance Criteria:**
- [x] Add Frontend Error catching of error 400
- [x] If error appears, prompt with refetch button
- [x] #12
- [x] Make the logo on the project page clickable
- [x] Fix enter button

**Comment by sandviklee** [comment]
Feedback: Make the logo on the project page clickable

**Comment by Spiderpig02** [comment]
Discovery: When implemented the error handeling from the API, I never got the 400 code, it only gave me the 500 code. I looked at the backend and the frontend code quickly, but did not see anything immediately wrong or strange there. Help?

**Comment by Spiderpig02** [comment]
@sandviklee  Could you explain the second acceptance criteria for me? I am, uncertain about if its already done

**Comment by sandviklee** [comment]
The point was to make it possible for the user to refetch if there was an error in the backend, with the same prompt. @Spiderpig02
