### ISSUE TITLE
Google maps won't work?

### ISSUE THREAD

**Issue by Spiderpig02** [CogitoNTNU/web-frontend#27]
The google maps part of the homePage 3, only says "For development purpose only", and gives a popup in the same window: "This page can't load Google Maps correctly".
I tried to se what's changed, perhaps from the ESLint changes, but uncertain how they could have made this to happen. 
From this post (https://stackoverflow.com/questions/50977913/google-maps-shows-for-development-purposes-only), it may appear to do with some billing things?

**Comment by sandviklee** [comment]
I am fixing this right now.

**Comment by sandviklee** [comment]
Fixed this now, just need to merge
