### ISSUE TITLE
Transition from Regular CSS to Responsive Tailwind CSS

### ISSUE THREAD

**Issue by sandviklee** [CogitoNTNU/web-frontend#3]
Using regular CSS has been a chore most of the time. Therefore I've come to the conclusion to change to Tailwind. It also opens up the possibility for easier responsiveness and darkmode. Tailwind CSS allows for faster development by using predefined utility classes, reducing the need to write custom CSS.

**Acceptance Criteria:**
- [x] Add Tailwind to the website
- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9
- [x] #10

**Comment by SverreNystad** [comment]
The site looks so good, amazing work!
